"""Abstract OTP provider interface.

All OTP providers (2Factor, Twilio, etc.) must implement this interface.
The otp_service.py module uses this abstraction so providers can be swapped
without changing any business logic.
"""

from abc import ABC, abstractmethod
from typing import TypedDict


class SendResult(TypedDict, total=False):
    success: bool
    provider_reference: str
    status: str
    error_code: str
    message: str


class VerifyResult(TypedDict, total=False):
    success: bool
    status: str
    error_code: str
    message: str


class OTPProvider(ABC):
    """Base class for OTP send/verify providers."""

    @abstractmethod
    def is_configured(self) -> bool:
        """Return True if the provider has valid credentials."""
        ...

    @abstractmethod
    def send(self, phone_e164: str, otp_code: str) -> SendResult:
        """Send an OTP to the given E.164 phone number.

        Args:
            phone_e164: Phone in +91XXXXXXXXXX format.
            otp_code: The OTP code to deliver (generated by caller).

        Returns a SendResult with at minimum:
            success, provider_reference (session id), status
        """
        ...

    @abstractmethod
    def verify(self, phone_e164: str, code: str, provider_reference: str) -> VerifyResult:
        """Verify a code against a previously sent OTP.

        Returns a VerifyResult with at minimum:
            success, status
        """
        ...
