"""2Factor.in OTP provider — SMS channel.

Official classic API (verified live against this account):
  Send SMS OTP (manual code)
    GET https://2factor.in/API/V1/{api_key}/SMS/{phone}/{otp}
    GET https://2factor.in/API/V1/{api_key}/SMS/{phone}/{otp}/{template_name}
    Response: {"Status":"Success","Details":"<session_id>"}

  Send SMS OTP (provider-generated code)
    GET https://2factor.in/API/V1/{api_key}/SMS/{phone}/AUTOGEN
    Response: {"Status":"Success","Details":"<session_id>"}

  Verify SMS OTP
    GET https://2factor.in/API/V1/{api_key}/SMS/VERIFY/{session_id}/{otp}
    Response: {"Status":"Success","Details":"OTP Matched"} | error details

Note: POST https://2factor.in/API/V1/OTP/SEND returns 404 on this account —
do not use that path.
"""

import logging
from typing import Optional

import httpx

from app.core.config import settings
from app.services.otp_provider import OTPProvider, SendResult, VerifyResult

logger = logging.getLogger("farmo.twofactor")

BASE_URL = "https://2factor.in/API/V1"


def _to_e164(phone: str) -> str:
    """Convert 10-digit Indian number to +91XXXXXXXXXX."""
    cleaned = phone.strip().replace(" ", "").replace("-", "")
    if cleaned.startswith("+91"):
        return cleaned
    if cleaned.startswith("91") and len(cleaned) == 12:
        return f"+{cleaned}"
    if len(cleaned) == 10 and cleaned.isdigit():
        return f"+91{cleaned}"
    raise ValueError(f"Invalid Indian phone number: {phone}")


def _to_local(phone: str) -> str:
    """Convert to bare 10-digit Indian number for classic path segments."""
    cleaned = phone.strip().replace(" ", "").replace("-", "")
    if cleaned.startswith("+91"):
        cleaned = cleaned[3:]
    elif cleaned.startswith("91") and len(cleaned) == 12:
        cleaned = cleaned[2:]
    if len(cleaned) != 10 or not cleaned.isdigit():
        raise ValueError(f"Invalid Indian phone number: {phone}")
    return cleaned


def _parse_status(data: dict) -> tuple[str, str]:
    status = str(data.get("Status") or data.get("status") or "")
    details = str(data.get("Details") or data.get("details") or data.get("message") or "")
    return status, details


def _safe_exc(exc: BaseException, *secrets: Optional[str]) -> str:
    """Stringify an exception while redacting API keys, OTPs and phone numbers.

    httpx exception messages embed the request URL, which for the 2Factor
    classic API contains the API key and the OTP in the path.
    """
    msg = f"{type(exc).__name__}: {exc}"
    for secret in (settings.TWOFACTOR_API_KEY, *secrets):
        if secret:
            msg = msg.replace(str(secret), "***")
    return msg


class TwoFactorOTP(OTPProvider):
    """2Factor.in SMS OTP provider implementation (classic GET API)."""

    def __init__(self) -> None:
        self._api_key: Optional[str] = settings.TWOFACTOR_API_KEY

    def is_configured(self) -> bool:
        return bool(self._api_key and self._api_key.strip())

    def send(self, phone_e164: str, otp_code: str) -> SendResult:
        """Send an OTP via 2Factor SMS manual path.

        Args:
            phone_e164: Phone in +91XXXXXXXXXX format.
            otp_code: The 6-digit OTP to send (generated by caller).
        """
        if not self.is_configured():
            return {
                "success": False,
                "error_code": "OTP_PROVIDER_NOT_CONFIGURED",
                "message": "2Factor API key not configured",
            }

        try:
            phone = _to_local(phone_e164)
            if not (otp_code and otp_code.isdigit()):
                raise ValueError("OTP must be numeric")
        except ValueError as exc:
            return {
                "success": False,
                "error_code": "INVALID_PHONE_NUMBER",
                "message": str(exc),
            }

        template = (settings.TWOFACTOR_SMS_TEMPLATE or "").strip()
        if template:
            # Manual OTP + DLT template name (SMS channel)
            url = f"{BASE_URL}/{self._api_key}/SMS/{phone}/{otp_code}/{template}"
        else:
            url = f"{BASE_URL}/{self._api_key}/SMS/{phone}/{otp_code}"

        try:
            resp = httpx.get(url, timeout=20.0)
            resp.raise_for_status()
            data = resp.json()
            status, details = _parse_status(data)

            if status.lower() == "success" and details:
                session_id = details
                logger.info(
                    "2Factor SMS OTP sent to %s, session=%s",
                    phone,
                    session_id[:8],
                )
                return {
                    "success": True,
                    "provider_reference": session_id,
                    "status": "sent",
                }

            logger.warning("2Factor send unexpected response: %s", data)
            error_msg = f"{status} {details}".lower()
            if "rate" in error_msg or "limit" in error_msg:
                return {
                    "success": False,
                    "error_code": "OTP_RATE_LIMITED",
                    "message": "Rate limited by provider",
                }
            if "template" in error_msg or "not found" in error_msg or "invalid" in error_msg:
                # Retry without template if template name is wrong for this account
                if template:
                    return self._send_without_template(phone, otp_code)
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider rejected the SMS request",
            }

        except httpx.HTTPStatusError as exc:
            logger.error(
                "2Factor HTTP %s: %s",
                exc.response.status_code,
                _safe_exc(exc, otp_code, phone, self._api_key),
            )
            code = exc.response.status_code
            if code == 401:
                return {
                    "success": False,
                    "error_code": "OTP_PROVIDER_NOT_CONFIGURED",
                    "message": "Invalid 2Factor API key",
                }
            if code == 429:
                return {
                    "success": False,
                    "error_code": "OTP_RATE_LIMITED",
                    "message": "Rate limited by provider",
                }
            if code == 404 and template:
                return self._send_without_template(phone, otp_code)
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider HTTP error",
            }

        except httpx.TimeoutException:
            logger.error("2Factor send timeout")
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider request timed out",
            }

        except Exception as exc:
            logger.error("2Factor send failed: %s", _safe_exc(exc, otp_code, phone, self._api_key))
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider send failed",
            }

    def _send_without_template(self, phone: str, otp_code: str) -> SendResult:
        url = f"{BASE_URL}/{self._api_key}/SMS/{phone}/{otp_code}"
        try:
            resp = httpx.get(url, timeout=20.0)
            resp.raise_for_status()
            data = resp.json()
            status, details = _parse_status(data)
            if status.lower() == "success" and details:
                return {
                    "success": True,
                    "provider_reference": details,
                    "status": "sent",
                }
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider rejected the SMS request",
            }
        except Exception as exc:
            logger.error("2Factor send (no template) failed: %s", _safe_exc(exc, otp_code, phone, self._api_key))
            return {
                "success": False,
                "error_code": "OTP_SEND_FAILED",
                "message": "Provider send failed",
            }

    def verify(self, phone_e164: str, code: str, provider_reference: str) -> VerifyResult:
        """Verify an OTP code via 2Factor classic SMS VERIFY endpoint."""
        if not self.is_configured():
            return {
                "success": False,
                "error_code": "OTP_PROVIDER_NOT_CONFIGURED",
                "message": "2Factor API key not configured",
            }

        url = f"{BASE_URL}/{self._api_key}/SMS/VERIFY/{provider_reference}/{code}"

        try:
            resp = httpx.get(url, timeout=20.0)
            resp.raise_for_status()
            data = resp.json()
            status, details = _parse_status(data)
            details_l = details.lower()
            status_l = status.lower()

            if status_l == "success" and (
                "match" in details_l or "verified" in details_l or not details_l
            ):
                logger.info("2Factor SMS OTP verified")
                return {"success": True, "status": "verified"}

            if status_l == "success":
                # Some responses return Success with any details on match
                if "not" not in details_l and "invalid" not in details_l and "expire" not in details_l:
                    return {"success": True, "status": "verified"}

            if "expired" in details_l or "expire" in details_l:
                return {
                    "success": False,
                    "error_code": "OTP_EXPIRED",
                    "status": "expired",
                }

            if ("max" in details_l and "attempt" in details_l) or "maximum" in details_l:
                return {
                    "success": False,
                    "error_code": "OTP_MAX_ATTEMPTS",
                    "status": "max_attempts_reached",
                }

            return {
                "success": False,
                "error_code": "OTP_VERIFICATION_FAILED",
                "status": "invalid",
            }

        except httpx.HTTPStatusError as exc:
            logger.error("2Factor verify HTTP %s", exc.response.status_code)
            return {
                "success": False,
                "error_code": "OTP_VERIFICATION_FAILED",
                "message": "Provider HTTP error",
            }

        except httpx.TimeoutException:
            logger.error("2Factor verify timeout")
            return {
                "success": False,
                "error_code": "OTP_VERIFICATION_FAILED",
                "message": "Provider request timed out",
            }

        except Exception as exc:
            logger.error("2Factor verify failed: %s", _safe_exc(exc, code, provider_reference, phone_e164, self._api_key))
            return {
                "success": False,
                "error_code": "OTP_VERIFICATION_FAILED",
                "message": "Provider verify failed",
            }


def get_twofactor_provider() -> TwoFactorOTP:
    """Factory for the 2Factor OTP provider."""
    return TwoFactorOTP()
